import Header from "@/components/header";
import "./globals.css";
import SubHeader from "@/components/subHeader";

export const metadata = {
  title: "Citynet",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <SubHeader/>
        {children}
      </body>
    </html>
  );
}
