import Header from "@/components/header";
import "./globals.css";
import SubHeader from "@/components/subHeader";
import Footer from "@/components/footer";

export const metadata = {
  title: "Citynet",
  description: "Generated by create next app",
  icons: {
    icon: '/LogoWebtitle.svg'
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <SubHeader />
        {children}
        <Footer />
      </body>
    </html>
  );
}
